### PR TITLE
Fix Daily Limit Check Timeout

### PR DESCRIPTION
**Pull request by TiagoSeverino**
This change is [Reviewable](https://reviewable.io/reviews/fawazahmed0/youtube-uploader/160)

### CODE REVIEW

**Comment by TiagoSeverino** [comment]
500ms is not enought to get the daily limit message, at least on my machine.
Usually takes 3s

**Comment by pierreminiggio** [comment]
I think it would be better to make that variable configurable.
Because it's basically the time we choose to wait before checking for errors.
And not everyone uploads videos of the same sizes, nor value in the same way how fast / slowly the package responds if it encounters one.

**Comment by fawazahmed0** [comment]
Increasing it will conflict with [this](https://github.com/fawazahmed0/youtube-uploader/blob/c34d632d852c4210855a7fdc014413eb40301021/src/upload.ts#L176) and it will cause whole program to stop indefinitely

**Comment by fawazahmed0** [comment]
PR #163 seems to add a better way of handling this thing

**Comment by fawazahmed0** [comment]
Thanks for your PR

**Pull request closed without merging**
