### PR TITLE
After switching chanel stuck at finding "selectBtn" because drop-down menu lack,

### PR DESCRIPTION
**Pull request by sacredrel1c**
This change is [Reviewable](https://reviewable.io/reviews/fawazahmed0/youtube-uploader/118)

### CODE REVIEW

**Comment by fawazahmed0** [comment]
I don't think this code will work, it has many issues. Please test it

**Review by fawazahmed0 — CHANGES_REQUESTED** [review]
You need to add await
```js
        if((await page.waitForXPath(createBtnXPath))){
            const createBtn = await page.$x(createBtnXPath);
            await createBtn[0].click();
        }
        if((await page.waitForXPath(addVideoBtnXPath))){
            const addVideoBtn =await page.$x(addVideoBtnXPath);
            await addVideoBtn[0].click();
        }
```
 after adding the requested changes, please test it.

**Comment by sacredrel1c** [comment]
i'm use vanilla js version, but i add yield instead of await

**Comment by sacredrel1c** [comment]
> Вам нужно добавить ожидание
> 
> ```js
>         if((await page.waitForXPath(createBtnXPath))){
>             const createBtn = await page.$x(createBtnXPath);
>             await createBtn[0].click();
>         }
>         if((await page.waitForXPath(addVideoBtnXPath))){
>             const addVideoBtn =await page.$x(addVideoBtnXPath);
>             await addVideoBtn[0].click();
>         }
> ```
> 
> после добавления запрошенных изменений проверьте его.

`const createBtnXPath = '//*[@id="create-icon"]/tp-yt-iron-icon';
        const addVideoBtnXPath = '//*[@id="text-item-0"]/ytcp-ve/div/div/yt-formatted-string';
        if(yield page.waitForXPath(createBtnXPath)){
            const createBtn = yield page.$x(createBtnXPath);
            createBtn[0].click();
        }
        if(yield page.waitForXPath(addVideoBtnXPath)){
            const addVideoBtn = yield page.$x(addVideoBtnXPath);
            addVideoBtn[0].click();
        }`


it work for me, and when i use other account i don't need this, because drop-down menu exist. and your code work fine.

**Comment by fawazahmed0** [comment]
I will merge this PR, after someone test it

**Comment by fawazahmed0** [comment]
Thanks for this PR

**Pull request merged**
