### PR TITLE
Added support for onProgress event.

### PR DESCRIPTION
**Pull request by DaddyFrosty**
Added a onProgress callback/option. Tested and works.

---
This change is [Reviewable](https://reviewable.io/reviews/fawazahmed0/youtube-uploader/60)

### CODE REVIEW

**Comment by fawazahmed0** [comment]
Thanks

**Comment by fawazahmed0** [comment]
I reverted this PR, because for some reason onProgress was throwing some error

**Comment by DaddyFrosty** [comment]
What's the error?

**Comment by fawazahmed0** [comment]
Here's the error
```
C:\Users\nawaz\Documents\GitHub\youtube-uploader\dist\upload.js:125
            videoJSON.onProgress(progress);
                      ^

TypeError: videoJSON.onProgress is not a function
    at C:\Users\nawaz\Documents\GitHub\youtube-uploader\dist\upload.js:125:23
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\nawaz\Documents\GitHub\youtube-uploader\dist\upload.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by DaddyFrosty** [comment]
Oh shit, when I went to bed I made a last change to send a 0% progress event upon starting the upload, and I forgot to make the if statement a block, and so it was calling code it shouldn't for a better explanation look at the changes but this should work.

**Pull request merged**
