### PR TITLE
stuck on upload page, because waiting for text - upload complete, and puppeter doesn't watch this, but i see this from my eyes

### PR DESCRIPTION
**Pull request by sacredrel1c**
changed waitting for text *Upload -> Processing* if skipProcessing:false, changed timeout, because timeout 0 sometimes stuck at upload page when video uploaded successfully, and add message to console.
timeout 0 it's bad variant, because it still waitting infinite.

---
This change is [Reviewable](https://reviewable.io/reviews/fawazahmed0/youtube-uploader/125)

### CODE REVIEW

**Comment by sacredrel1c** [comment]
> Have you tested it for large videos (i.e 1-2GB video size) ?

I'm not sure, because i use small videos (30-50mb), maybe need additional checks (i.e await another xPath, like text status in top of pop-up page) maybe I'll think about it and present better solution.

**Comment by sacredrel1c** [comment]
i analyzed previous code, and found right xPath-text to more stability. And fix processing xpath-text.

**Comment by fawazahmed0** [comment]
I will merge this after someone tests it for large videos

**Comment by murqlegend** [comment]
please merge this i have the same problem and this is the only solution

**Comment by fawazahmed0** [comment]
Thanks once again for the PR

**Pull request merged**
