### PR TITLE
Fixed #60

### PR DESCRIPTION
**Pull request by DaddyFrosty**
Fixed #60

---
This change is [Reviewable](https://reviewable.io/reviews/fawazahmed0/youtube-uploader/62)

### CODE REVIEW

**Comment by fawazahmed0** [comment]
`npm run build`  gives me this error:
```

src/upload.ts:146:23 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(intervalId: Timeout): void', gave the following error.
    Argument of type 'Timer | undefined' is not assignable to parameter of type 'Timeout'.
      Type 'undefined' is not assignable to type 'Timeout'.
  Overload 2 of 2, '(handle?: number | undefined): void', gave the following error.
    Argument of type 'Timer | undefined' is not assignable to parameter of type 'number | undefined'.
      Type 'Timer' is not assignable to type 'number'.

146         clearInterval(progressChecker)
                          ~~~~~~~~~~~~~~~



Found 1 error.

```

**Comment by DaddyFrosty** [comment]
Seems like the type is broken, I've tested clearInterval with any in a sandbox so it should be fine.

**Comment by DaddyFrosty** [comment]
and I tried compiling it, went fine using a clone of the repo, sorry for the waste of time in case this works.

**Comment by fawazahmed0** [comment]
working fine now

**Pull request merged**
