### PR TITLE
Fix "Couldn't sign you in" Google login errors

### PR DESCRIPTION
**Pull request by Chipped1**
This PR introduces a fix for issues #119 and #126 by disabling the `iframe.contentWindow` and `navigator.plugins` evasion methods

---
This change is [Reviewable](https://reviewable.io/reviews/fawazahmed0/youtube-uploader/127)

### CODE REVIEW

**Review by murqlegend — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fawazahmed0/youtube-uploader/127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chipped1)

**Comment by murqlegend** [comment]
Hello,

Is there a more detailed article for me and ignorant people like me? Because we are really ignorant of github, we are very confused how to branch.

**Comment by murqlegend** [comment]
All I can do is write "npm i youtube-videos-uploader" in visual studio code and add a library, but the last settings you made are not coming, so it gives a browser error. What can I do?

**Comment by Chipped1** [comment]
> All I can do is write "npm i youtube-videos-uploader" in visual studio code and add a library, but the last settings you made are not coming, so it gives a browser error. What can I do?

You should be able to do `npm i @chipped/youtube-videos-uploader@1.3.63-evasion`

**Comment by fawazahmed0** [comment]
Thanks for this PR

**Comment by murqlegend** [comment]
Everything worked smoothly, but now the video title does not enter where it should be entered, it stops, it does not work, why do you think it does it when you turn it on and off 8-9 times?

**Pull request merged**
